apiVersion: v2
name: istio-default
version: 1.0.0
appVersion: 1.0.0
description: Helm chart for istio default revision components.
keywords:
  - istio
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
