apiVersion: v2
name: cni
version: 1.13.3
appVersion: "1.13.3-tetrate-multiarch-v1"
description: Helm chart for istio-cni components
keywords:
  - istio-cni
  - istio
sources:
  - http://github.com/istio/cni
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
