apiVersion: v2
name: istio-operator
version: 1.13.5
appVersion: 1.13.5-tetrate-multiarch-v1
description: Helm chart for deploying Istio operator
keywords:
  - istio
  - operator
sources:
  - https://github.com/istio/istio/tree/master/operator
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
