apiVersion: v1
name: istio-operator
# This version is never actually shipped. istio/release-builder will replace it at build-time
# with the appropriate version
version: 1.16.1-tetrate-v0
appVersion: 1.16.1-tetrate-v0
description: Helm chart for deploying Istio operator
keywords:
  - istio
  - operator
sources:
  - https://github.com/istio/istio/tree/master/operator
icon: https://istio.io/latest/favicons/android-192x192.png
