apiVersion: v1
entries:
  base:
  - apiVersion: v2
    appVersion: 1.13.5-tetrate-multiarch-v1
    created: "2022-06-16T12:38:03.70393-06:00"
    description: Helm chart for deploying Istio cluster resources and CRDs
    digest: 3e86a68028c040990588fb33ed80e4fd8f42f1b6e91bf2683e80ca1af3ae26bc
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    name: base
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/base-1.13.5/base-1.13.5.tgz
    version: 1.13.5
  - apiVersion: v2
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:41:27.272738-06:00"
    description: Helm chart for deploying Istio cluster resources and CRDs
    digest: 3da21b4dc52a7858133d17919fd83bc0f9af341d89406304f8b79d76bbff14d2
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    name: base
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/base-1.13.3/base-1.13.3.tgz
    version: 1.13.3
  - apiVersion: v1
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:29:44.206676-06:00"
    description: Helm chart for deploying Istio cluster resources and CRDs
    digest: 145144be8c50ee511a1643035857fdf4437d5b4b5da42fdc832c2ae2c275dacf
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    name: base
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/base-1.13.3-tetrate-multiarch-v1/base-1.13.3-tetrate-multiarch-v1.tgz
    version: 1.13.3-tetrate-multiarch-v1
  cni:
  - apiVersion: v2
    appVersion: 1.13.5-tetrate-multiarch-v1
    created: "2022-06-16T12:38:03.847299-06:00"
    description: Helm chart for istio-cni components
    digest: 4ef1a6118868082672b114762b58a779d0b69a0129337cdf5d8b1d7e6a3d7ef4
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio-cni
    - istio
    name: cni
    sources:
    - http://github.com/istio/cni
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/cni-1.13.5/cni-1.13.5.tgz
    version: 1.13.5
  - apiVersion: v2
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:41:27.535288-06:00"
    description: Helm chart for istio-cni components
    digest: 847618d9cba8e33258320ec379b159d16473bbe1fc4450845277efbb54665272
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio-cni
    - istio
    name: cni
    sources:
    - http://github.com/istio/cni
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/cni-1.13.3/cni-1.13.3.tgz
    version: 1.13.3
  - apiVersion: v1
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:29:44.448435-06:00"
    description: Helm chart for istio-cni components
    digest: 47411cd06f8efdb4e09b85f986f97a614bcf2c9c44157a9a3bd5be4282a65885
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio-cni
    - istio
    name: cni
    sources:
    - http://github.com/istio/cni
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/cni-1.13.3-tetrate-multiarch-v1/cni-1.13.3-tetrate-multiarch-v1.tgz
    version: 1.13.3-tetrate-multiarch-v1
  gateway:
  - apiVersion: v2
    appVersion: 1.13.5-tetrate-multiarch-v1
    created: "2022-06-30T00:10:31.23203-06:00"
    description: Helm chart for deploying Istio gateways
    digest: f802337da3bda7a3c9ed62d5bf91d58251e54dfedfe0977a610aed111e0f9f14
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - gateways
    name: gateway
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/gateway-1.13.5/gateway-1.13.5.tgz
    version: 1.13.5
  - apiVersion: v2
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-30T00:10:31.107926-06:00"
    description: Helm chart for deploying Istio gateways
    digest: 14b5cfa3272b59d38f2041a3fc65beafc2fc55ddac77a8d22377c61ee36451b6
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - gateways
    name: gateway
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/gateway-1.13.3/gateway-1.13.3.tgz
    version: 1.13.3
  istio-default:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-06-16T12:38:03.981754-06:00"
    description: Helm chart for istio default revision components.
    digest: 59266a620834c0fc842ff05a55e401b155d9c92b64029afb013b82822f7ef86b
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    name: istio-default
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-default-1.0.0/istio-default-1.0.0.tgz
    version: 1.0.0
  istio-egress:
  - apiVersion: v2
    appVersion: 1.13.5-tetrate-multiarch-v1
    created: "2022-06-16T12:38:04.109655-06:00"
    description: Helm chart for deploying Istio gateways
    digest: 9b31c512c649ace1b0f0f9ce13adfb64cdbb798b20f72a6f3bcbec391fe107cf
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - egressgateway
    - gateways
    name: istio-egress
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-egress-1.13.5/istio-egress-1.13.5.tgz
    version: 1.13.5
  - apiVersion: v2
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:41:28.019601-06:00"
    description: Helm chart for deploying Istio gateways
    digest: 25cee358769cfa9018902a7f7e46e940b07a5cf3c3cb805f4853bba0636903e6
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - egressgateway
    - gateways
    name: istio-egress
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-egress-1.13.3/istio-egress-1.13.3.tgz
    version: 1.13.3
  - apiVersion: v1
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:29:44.813931-06:00"
    description: Helm chart for deploying Istio gateways
    digest: 2699adc02f2a7cdf12fa59e8f11c4248148efd1e73fb9c5215d5c6f1af547613
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - egressgateway
    - gateways
    name: istio-egress
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-egress-1.13.3-tetrate-multiarch-v1/istio-egress-1.13.3-tetrate-multiarch-v1.tgz
    version: 1.13.3-tetrate-multiarch-v1
  istio-ingress:
  - apiVersion: v2
    appVersion: 1.13.5-tetrate-multiarch-v1
    created: "2022-06-16T12:38:04.253893-06:00"
    description: Helm chart for deploying Istio gateways
    digest: bbc602a3eb68a0a4549219187a02c1feb939b10259947dcdf69f1cbce7c842e8
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - ingressgateway
    - gateways
    name: istio-ingress
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-ingress-1.13.5/istio-ingress-1.13.5.tgz
    version: 1.13.5
  - apiVersion: v2
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:41:28.252535-06:00"
    description: Helm chart for deploying Istio gateways
    digest: d8b9557fe88f0d17d5df57a94f68fb205242a9f52d9d252f94d11b495cb88448
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - ingressgateway
    - gateways
    name: istio-ingress
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-ingress-1.13.3/istio-ingress-1.13.3.tgz
    version: 1.13.3
  - apiVersion: v1
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:29:45.053286-06:00"
    description: Helm chart for deploying Istio gateways
    digest: 64ac6aebf83f7904e94a5277599bbea4e1b7368d897225870c88cf3c12690beb
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - ingressgateway
    - gateways
    name: istio-ingress
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-ingress-1.13.3-tetrate-multiarch-v1/istio-ingress-1.13.3-tetrate-multiarch-v1.tgz
    version: 1.13.3-tetrate-multiarch-v1
  istio-operator:
  - apiVersion: v2
    appVersion: 1.13.5-tetrate-multiarch-v1
    created: "2022-06-16T12:38:04.381697-06:00"
    description: Helm chart for deploying Istio operator
    digest: 3ed5ec3b0bd763562f7f3f622feabe2a93e18c44eaa09ad099f5f899a02141ec
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - operator
    name: istio-operator
    sources:
    - https://github.com/istio/istio/tree/master/operator
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-operator-1.13.5/istio-operator-1.13.5.tgz
    version: 1.13.5
  - apiVersion: v2
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:41:28.48863-06:00"
    description: Helm chart for deploying Istio operator
    digest: d14025d5d7cf07501aea6c92ee09c7d09769cf8141d4dcb99ef9b3c5968f3e56
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - operator
    name: istio-operator
    sources:
    - https://github.com/istio/istio/tree/master/operator
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-operator-1.13.3/istio-operator-1.13.3.tgz
    version: 1.13.3
  - apiVersion: v1
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:29:45.289291-06:00"
    description: Helm chart for deploying Istio operator
    digest: 6f4e00f08b0abdd572a1e20f99bd600eee6f31874cc6a3805bfaed038743af87
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - operator
    name: istio-operator
    sources:
    - https://github.com/istio/istio/tree/master/operator
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istio-operator-1.13.3-tetrate-multiarch-v1/istio-operator-1.13.3-tetrate-multiarch-v1.tgz
    version: 1.13.3-tetrate-multiarch-v1
  istiod:
  - apiVersion: v2
    appVersion: 1.13.5-tetrate-multiarch-v1
    created: "2022-06-16T12:38:04.510441-06:00"
    description: Helm chart for istio control plane
    digest: c0090eae57ddf1d835b44892fceac3292d3386196644ee59972f530e0a7c0283
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - istiod
    - istio-discovery
    name: istiod
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istiod-1.13.5/istiod-1.13.5.tgz
    version: 1.13.5
  - apiVersion: v2
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:41:28.7273-06:00"
    description: Helm chart for istio control plane
    digest: b4b8a467929b4f7c1aa50022b6679665a97815ed1417810713124318e552d2d8
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - istiod
    - istio-discovery
    name: istiod
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istiod-1.13.3/istiod-1.13.3.tgz
    version: 1.13.3
  - apiVersion: v1
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:29:45.552329-06:00"
    description: Helm chart for istio control plane
    digest: 9cd2a8783f5f6f00e19547630aa28b7bfa9e142c2f8e1190a14323027126808a
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - istiod
    - istio-discovery
    name: istiod
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istiod-1.13.3-tetrate-multiarch-v1/istiod-1.13.3-tetrate-multiarch-v1.tgz
    version: 1.13.3-tetrate-multiarch-v1
  istiod-remote:
  - apiVersion: v2
    appVersion: 1.13.5-tetrate-multiarch-v1
    created: "2022-06-16T12:38:04.64105-06:00"
    description: Helm chart for a remote cluster using an external istio control plane
    digest: f21e546f6b826fbda746611da2929f5b4540191c993ea4d81801252ea1679d13
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - external-istiod
    name: istiod-remote
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istiod-remote-1.13.5/istiod-remote-1.13.5.tgz
    version: 1.13.5
  - apiVersion: v2
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:41:28.98832-06:00"
    description: Helm chart for a remote cluster using an external istio control plane
    digest: c54c72b1be665def3fc130890ab58f11558b8649c99a40b9b9804bb9decc4e08
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - external-istiod
    name: istiod-remote
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istiod-remote-1.13.3/istiod-remote-1.13.3.tgz
    version: 1.13.3
  - apiVersion: v1
    appVersion: 1.13.3-tetrate-multiarch-v1
    created: "2022-06-16T18:29:45.814958-06:00"
    description: Helm chart for a remote cluster using an external istio control plane
    digest: 49638f47c43aab05bf3d62c7086cfd1a60f639b851c6da67671c7e4c86292e1a
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - external-istiod
    name: istiod-remote
    sources:
    - http://github.com/istio/istio
    urls:
    - https://github.com/psbrar99/helmchart/releases/download/istiod-remote-1.13.3-tetrate-multiarch-v1/istiod-remote-1.13.3-tetrate-multiarch-v1.tgz
    version: 1.13.3-tetrate-multiarch-v1
generated: "2022-06-30T00:10:31.232113-06:00"
