apiVersion: v2
name: istio-ingress
version: 1.13.3
appVersion: "1.13.3-tetrate-multiarch-v1"
description: Helm chart for deploying Istio gateways
keywords:
  - istio
  - ingressgateway
  - gateways
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
