name: Release Charts

on:
  push:
    tags:
      - "1.*"
jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "psbrar99"
          git config user.email "psbrar99@users.noreply.github.com"
      - name: Get the tag
        id: get_tag
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: RELEASE_TAG
        env: 
          VERSION: ${{ steps.get_tag.outputs.VERSION }}
        id: release_tag
        run: |
          echo ::set-output name=RELEASE_TAG::$(echo $RELEASE_TAG | sed 's/-.*//g')
      
      - name: Get the charts
        env: 
          VERSION: ${{ steps.get_tag.outputs.VERSION }}
          RELEASE_TAG: ${{ steps.release_tag.outputs.RELEASE_TAG}}
        run: |
          curl -O "https://dl.getistio.io/public/raw/files/istio-$VERSION-linux-amd64.tar.gz"
          tar -xvzf istio-$VERSION-linux-amd64.tar.gz
          mkdir -p charts/istio-$RELEASE_TAG
          cp -rf ./istio-$VERSION/manifests/charts/* charts/istio-$RELEASE_TAG
          find ./charts/istio-$RELEASE_TAG -name 'Chart.yaml'  -type f -exec yq -i '.version=env(RELEASE_TAG)' {} \;
          sed -i '/\$whv := dict/,8d' charts/istio-$RELEASE_TAG/istio-control/istio-discovery/templates/revision-tags.yaml
          sed -e '4i {{- $whv := dict "revision" .Values.revision "injectionPath" .Values.istiodRemote.injectionPath "injectionURL" .Values.istiodRemote.injectionURL "namespace" .Release.Namespace }}' -i charts/istio-$RELEASE_TAG/istio-control/istio-discovery/templates/revision-tags.yaml
          sed -i '/\$whv := dict/,7d' charts/istio-$RELEASE_TAG/istio-control/istio-discovery/templates/mutatingwebhook.yaml
          sed -e '3i {{- $whv := dict "revision" .Values.revision "injectionPath" .Values.istiodRemote.injectionPath "injectionURL" .Values.istiodRemote.injectionURL "namespace" .Release.Namespace }}'  -i charts/istio-$RELEASE_TAG/istio-control/istio-discovery/templates/mutatingwebhook.yaml
          rm -rf istio-$VERSION/-*
      - name: Commit changes
        env: 
          VERSION: ${{ steps.get_tag.outputs.VERSION }}
        uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub Actions logo
          committer_name: GitHub Actions
          committer_email: actions@github.com
          new_branch: ${{env.VERSION}}-istio
          push: true
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Package chart Helm
        env: 
          VERSION: ${{ steps.get_tag.outputs.VERSION }}
        run : |
          helm package charts/istio-$RELEASE_TAG/{base,default,gateway,gateways/istio-ingress,gateways/istio-egress,istio-cni,istio-control/istio-discovery,istio-operator,istiod-remote} --destination .deploy
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
          charts_repo_url: https://psbrar99.github.io/helmchart/
          config: cr.yaml
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.RELEASE_SECRET }}"
